### ISSUE TITLE
Warning en cas de date de naissance inchangée

### ISSUE THREAD

**Issue by LePelicaN** [LePelicaN/Depistage#10]
Rajouter un pop-up lors de la réalisation si la date de naissance n'a pas été changée : « Vous lancez un test VIH d'un patient né le 01/01/2000. Continuez la génération ? »

**Comment by LePelicaN** [comment]
On parle de TROD ou etiquette ici ?

**Comment by feydriva** [comment]
De TROD !

**Comment by LePelicaN** [comment]
Version de test livrée.

**Comment by feydriva** [comment]
Ca a l'air de très bien fonctionner ça.
Vérification au prochain vrai test.

**Comment by feydriva** [comment]
Ca a l'air de très bien fonctionner ça (à part le 1er des tests quand on démarre le programme).

**Comment by feydriva** [comment]
Royal
