### ISSUE TITLE
Ajout d'un test positif TROD et TOYO

### ISSUE THREAD

**Issue by feydriva** [LePelicaN/Depistage#11]
Explication : quand j'ai un résultat positif (vih ou vhc) que je puisse imprimer ce résultat (donc 2 autres documents word modèles), que ça rentre bien dans le même tableau excel que les négatifs (sauf qu'en plus dans une colonne il y est écrit "positif" (colonne F) et que pour TROD ça m'enregistre le résultat dans un autre dossier que les négatifs et pour TOYO dans le même dossier.

Que ça ne reste pas coché pour le suivant.

Dès qu'on clique sur cette checkbox ouvrir un popup "Attention, test positif ? Continuer ?"
Si oui -> ne rien faire
Si non -> décocher

**Comment by feydriva** [comment]
Dès qu'on clique sur cette checkbox ouvrir un popup "Attention test positif ? Continuer ?"

**Comment by feydriva** [comment]
Préciser la colonne du document excel ou noter "positif".

**Comment by LePelicaN** [comment]
Le développement nécessite plus d'information :
- Où se situe cette checkbox dans l'écran ?
- Quel label a cette checkbox ?

**Comment by LePelicaN** [comment]
Version de test livrée.

**Comment by feydriva** [comment]
Alors en fait ta

**Comment by feydriva** [comment]
Alors d'abord en fait ta phrase est plus professionnelle : 
"Vous lancez un test positif. Continuez la génération ? 
(Dans ce cas penser à noter le numéro de lot.)" 
Méa culpa

Ensuite ça ne décoche pas après la réalisation du test le bouton positif.

Et enfin l'onglet TOYO ne fonctionne plus, cad quand je clique sur "lancer génération" ça me dit "attention vous lancez un test VHC" et après ça ne fait rien du tout...

**Comment by feydriva** [comment]
Alors d'abord en fait ta phrase est plus professionnelle : 
"Vous lancez un test positif. Continuez la génération ? 
(Dans ce cas penser à noter le numéro de lot.)" 
Méa culpa

Ensuite un seul avertissement suffit quand on coche la case positif en fait.

Ensuite ça ne décoche pas après la réalisation du test le bouton positif.

Ensuite l'onglet TOYO ne fonctionne plus, cad quand je clique sur "lancer génération" ça me dit "attention vous lancez un test VHC" et après ça ne fait rien du tout...
(C'est pourquoi je vais mettre bug :))

**Comment by LePelicaN** [comment]
Je ne suis d'accord ni avec 1), ni avec 2) :
- Pour le 1), au moment où tu coches, tu ne lances pas un test donc ni "Vous lancez un test" ni "Continuez la génération" ne fait sens à mes yeux.
- Pour le 2), si il ne faut le garder qu'à un endroit, c'est lors de la génération. Car sinon tu peux sélectionner positif, faire autre chose puis générer et tu n'as aucun warning.
Le 3) est corrigé et livré.
Le 5) tu me crée un nouveau ticket s'il te plait.

**Comment by feydriva** [comment]
Ok pour tes remarques : un seul avertissement au moment de la génération 
"Vous lancez un test positif. Continuez la génération ?"

**Comment by feydriva** [comment]
Bon on n'a pas le droit d'être 2 assignés sur la même tache mais moi j'ai oublié de vérifier si dans excel dans la colonne F il y avait bien écrit positif. A vérifier donc.

**Comment by feydriva** [comment]
Je teste demain début d'aprèm mais sur cette issue là il te reste à supprimer l'un des avertissements :
Un seul avertissement au moment de la génération : "Vous lancez un test positif. Continuez la génération ?"

**Comment by LePelicaN** [comment]
Il ne reste qu'un warning. Version de test livrée.

**Comment by feydriva** [comment]
Il ne reste qu'un warning c'est bon.

Pour le rajout de "positif" dans le document excel ça fonctionne, on peut plutôt mettre "POSITIF" en fait STP ?

**Comment by feydriva** [comment]
Punaise je n'arrive rien à faire au boulot, mémo pour moi : te réassigner cette tache.

**Comment by LePelicaN** [comment]
Version de test livrée.

**Comment by feydriva** [comment]
Validé !
