### ISSUE TITLE
Version du 10/3 soir à débugger (TROD-TOYO)

### ISSUE THREAD

**Issue by feydriva** [LePelicaN/Depistage#12]
J'ai téléchargé le programme d'hier soir.
Je l'ai appelé Depistage avril 2015.exe
Je le lance.
Je mets des données.
 
Ca ne marche pas, cad que quand je clique sur "Lancer génération", ça ne fait rien du tout pour l'onglet TROD, et ça m'ouvre le pop-up comme quoi je fais un test VHC côté TOYO et ça s'arrête là aussi.

J'ai tenté de faire la même chose avec la version du 8/03. Résultat identique.

**Comment by LePelicaN** [comment]
Bug corrigé. Version de test fournie.

**Comment by feydriva** [comment]
C'est re-bon je le met en prod (pour moi ça veut dire qu'il remplace la version utilisée tous les jours)
