### ISSUE TITLE
Alerte ligne "numéro de lot" vide (TROD positif)

### ISSUE THREAD

**Issue by feydriva** [LePelicaN/Depistage#13]
Il faudrait rajouter une alerte uniquement pour l'onglet TROD, uniquement quand la case "Positif" est cochée, uniquement si la ligne "numéro de lot" est vide, il faudrait que quand on clique sur "lancer génération" ça dise "Vous lancez un test positif sans numéro de lot. Continuez la génération ?"

**Comment by LePelicaN** [comment]
Et pas pour TOYO ? Pourquoi ?

**Comment by feydriva** [comment]
Parce que les TROD on en commande 200 par mois, donc on change régulièrement le numéro de lot mais on le change directement dans le document modèle 1 fois par mois.
Du coup le document modèle TROD positif à l'inverse il faudra rentrer le numéro de lot à la main.

A l'inverse les TOYO on a commandé il y a 1 an une boite de 50 et on ne l'a pas fini. Donc quand je fais des tests (négatifs ou positifs) c'est le même lot donc il est noté dans le document modèle.

**Comment by LePelicaN** [comment]
Ça ne ferait pas de mal si on avait la phrase dans les deux, si ?

**Comment by feydriva** [comment]
Ah mais oui en fait c'est toi qui a raison ! Ce n'est pas le même document modèle le positif et le négatif donc il faudra le rentrer aussi ! Exact !
(Je ne comprend pas pourquoi toi ça t'a semblé logique et pas moi...)

**Comment by LePelicaN** [comment]
Version de test livrée.

**Comment by feydriva** [comment]
Validé !
