### ISSUE TITLE
Impression d'une étiquette en moins que le nombre demandé (Onglet Etiquette)

### ISSUE THREAD

**Issue by feydriva** [LePelicaN/Depistage#19]
L'utilisatrice pense que dans la version du 17/03 ce bug n'existait plus.
L'utilisatrice avait tort.

Sinon, avec la version du jour : on lance l'impression et ça imprime un code en moins que le nombre demandé. Je demande 3 codes en partant de AAA, ça m'imprime AAA et AAB.

Par contre cela en imprime une si on n'en demande qu'une (avec la date de naissance).

**Comment by LePelicaN** [comment]
Version de test livrée.

**Comment by feydriva** [comment]
Ok !
