### ISSUE TITLE
Pas d'impression pour une seule planche d'étiquettes

### ISSUE THREAD

**Issue by feydriva** [LePelicaN/Depistage#4]
Quand on utilise l'onglet Etiquettes, pour créer une seule planche d'étiquettes (donc avec une date de naissance), ça a l'air de tout bien fonctionner mais ça n'imprime pas.

**Comment by feydriva** [comment]
Il y a des ordis plus rapide que d'autres ou ça fonctionne et d'autres non... 
À voir ensemble demain !

**Comment by LePelicaN** [comment]
On en est où là ?

**Comment by feydriva** [comment]
Alors je clique sur "Lancer génération".
Ca m'ouvre le document word rempli.
Ca m'ouvre le cadre intitulé "Imprimer" (celui ou je choisis mon bac de papier) (correspond au doc1 reçu par mail ce jour, je modifierais ce commentaire arrivée chez moi)
Ensuite je clique sur OK, s'affiche la petite fenêtre "Ce document a été envoyé à l'imprimante" (doc2).
Puis le document word se ferme et rien ne s'imprime.

Par contre pour les étiquettes multiples de nouveau on a une étiquette en moins qui s'imprime malgré l'apparition du bouton "Validez lorque l'impression est terminée" doc3, bouton qui n'apparait pas dans le cas au dessus.

**Comment by feydriva** [comment]
(Donc je pense comme une étiquette en moins est imprimée quand j'en demande 2, et ben il y en a zéro quand j'en demande 1, c'est logique...)

**Comment by feydriva** [comment]
2 correctifs :

- Pour les étiquettes uniques quelques unes se sont finalement imprimées (mais plusieurs minutes après).

- Pour les étiquettes multiples : toujours une en moins mais pas sur le même bac alors que je n'ai touché à rien sur les options d'impression...

**Comment by feydriva** [comment]
Bon les étiquettes uniques finalement ça fonctionne, peut-être qu'il n'y avait plus de papier (MODE GROS BOULET ON).
Par contre sans fenêtre "Validez lorque l'impression est terminée".

Pour les étiquettes multiples : toujours une en moins.

**Comment by LePelicaN** [comment]
Ça existe toujours ça ?

**Comment by LePelicaN** [comment]
Tu n'as pas répondu à ça !
