### ISSUE TITLE
Info transférées de TROD vers TOYO

### ISSUE THREAD

**Issue by feydriva** [LePelicaN/Depistage#5]
1) Quand on fait à la fois un test VIH (onglet TROD) et un test VHC (onglet TOYO), on crée d'abord le résultat VIH, et il faudrait que les données qu'on vient de rentrer se copient collent dans la fenêtre TOYO.
2) Quand on utilise l'onglet TOYO, il faudrait qu'apparaisse une petite fenêtre "Vous êtes en train de faire un test VHC, si c'est une erreur cliquer sur l'onglet TROD" au moment ou on clique sur "Lancer génération" (et pas au moment ou on clique sur l'onglet Toyo parce que justement c'est parce qu'on est déjà dessus qu'on se plante.
Ou alors une fois qu'on a cliqué sur "Lancer génération" dans l'onglet TOYO que ça nous remette sur l'onglet TROD...

**Comment by LePelicaN** [comment]
Point 1 terminé. Une version a été fourni pour les tests.

**Comment by feydriva** [comment]
Point 2 : c'est bon !
Point 1 : erreur de description de la tâche : il faut que les données qu'on rentre dans TROD se copient collent dans la fenêtre TOYO sauf la ligne "Numéro de lot".

**Comment by feydriva** [comment]
Point 2 : ok !

Point 1 : erreur dans les spécifications : quand on fait à la fois un test VIH (onglet TROD) et un test VHC (onglet TOYO), on crée d'abord le résultat VIH, et il faudrait que les données qu'on vient de rentrer se copient collent dans la fenêtre TOYO sauf la ligne "Numéro de lot".

**Comment by LePelicaN** [comment]
Nouvelle version proposée.

**Comment by feydriva** [comment]
Royal !

**Comment by feydriva** [comment]
Et en plus, ça ne pourrait pas quand même me rebasculer sur l'onglet TROD après avoir cliqué sur "lancer génération" dans l'onglet "TOYO" ?

**Comment by feydriva** [comment]
Nouvelle issue créée.
