### ISSUE TITLE
Mettre tous les inputs textuel en capital

### ISSUE THREAD

**Issue by feydriva** [LePelicaN/Depistage#6]
Faire que tout soit écrit en majuscule d'office

**Comment by LePelicaN** [comment]
Retour de Feydriva : tout les inputs texte doivent être en majuscule.

**Comment by LePelicaN** [comment]
Dev' fini. Version de test livré.

**Comment by feydriva** [comment]
C'est bon aussi !

**Comment by feydriva** [comment]
Oubli d'une spécification : mettre en majuscule d'office aussi le code patient de l'onglet Étiquettes.

**Comment by LePelicaN** [comment]
Version de test fourni.

**Comment by feydriva** [comment]
Ca a l'air bon.
Vérification lors du prochain vrai test.
