### ISSUE TITLE
Permettre la sélection du chemin vers les différents fichiers à la main

### ISSUE THREAD

**Issue by LePelicaN** [LePelicaN/Depistage#8]
Afin de pouvoir mettre des adresses réseaux, il serait nécessaire de permettre de rentrer l'adresse des fichiers à la main sans avoir à éditer le fichier de config manuellement.

**Comment by LePelicaN** [comment]
Version de test fourni.

**Comment by feydriva** [comment]
1er essai ça a l'air top
confirmation lors d'un vrai test complet à venir
